const canvas=document.getElementById('sky');
if(canvas){
const ctx=canvas.getContext('2d',{alpha:true});
const plate=new Image(),buf=document.createElement('canvas'),bctx=buf.getContext('2d',{willReadFrequently:true});
const darkMQ=matchMedia('(prefers-color-scheme: dark)'),motionMQ=matchMedia('(prefers-reduced-motion: reduce)');
const SRC='/assets/annapurna-circuit.jpg',MAX_DPR=2,B=[0,48,12,60,3,51,15,63,32,16,44,28,35,19,47,31,8,56,4,52,11,59,7,55,40,24,36,20,43,27,39,23,2,50,14,62,1,49,13,61,34,18,46,30,33,17,45,29,10,58,6,54,9,57,5,53,42,26,38,22,41,25,37,21];
const T={dark:{ink:'#e4dac8',a:.91,dust:.22,cloud:.17,star:'#eee6d8'},light:{ink:'#293039',a:.86,dust:.12,cloud:.24,star:'#293039'}};
let S=null,terrain=null,dust=[],clouds=[],stars=[],raf=0,last=0,resizeTimer=0,reduced=motionMQ.matches,visible=!document.hidden;
let comet={active:false,start:0,duration:0,next:Infinity,x0:0,y0:0,x1:0,y1:0,tail:0};
const clamp=(v,a,b)=>v<a?a:v>b?b:v,lerp=(a,b,t)=>a+(b-a)*t;
function smooth(a,b,v){let t=clamp((v-a)/(b-a),0,1);return t*t*(3-2*t)}
function hash(v){v=Math.imul(v^(v>>>16),2246822507);v=Math.imul(v^(v>>>13),3266489909);return((v^(v>>>16))>>>0)/4294967296}
function h2(x,y,s){return hash(Math.imul(x|0,374761393)^Math.imul(y|0,668265263)^Math.imul(s|0,2246822519))}
function noise(x,y,s){let ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,ux=fx*fx*(3-2*fx),uy=fy*fy*(3-2*fy),a=h2(ix,iy,s),b=h2(ix+1,iy,s),c=h2(ix,iy+1,s),d=h2(ix+1,iy+1,s);return lerp(lerp(a,b,ux),lerp(c,d,ux),uy)}
function fbm(x,y,s){let v=0,a=.58,f=1,n=0;for(let i=0;i<4;i++){v+=noise(x*f,y*f,s+i*97)*a;n+=a;f*=2.03;a*=.47}return v/n}
function field(x,y,t,s){let q=fbm(x-t*.18,y+t*.11,s);return fbm(x+q*.72+t*.16,y+q*.48-t*.1,s+211)}
function median(a){a.sort((x,y)=>x-y);return a[Math.floor(a.length/2)]||0}
function theme(){return darkMQ.matches?T.dark:T.light}
function bayer(x,y){return B[((y%8+8)%8)*8+((x%8+8)%8)]/64}
function skyMask(px,w,h,top,drawH,dpr){
 let rs=[],gs=[],bs=[],bottom=Math.min(h-1,top+Math.max(8,Math.round(drawH*.075))),xs=Math.max(1,Math.floor(w/180)),ys=Math.max(1,Math.floor((bottom-top+1)/10));
 for(let y=top;y<=bottom;y+=ys)for(let x=0;x<w;x+=xs){let p=(y*w+x)*4;rs.push(px[p]);gs.push(px[p+1]);bs.push(px[p+2])}
 let rr=median(rs),rg=median(gs),rb=median(bs),rl=rr*.2126+rg*.7152+rb*.0722,rbg=rb-rg,rgr=rg-rr;
 const score=i=>{let p=i*4,r=px[p],g=px[p+1],b=px[p+2],l=r*.2126+g*.7152+b*.0722;return Math.abs((b-g)-rbg)*1.55+Math.abs((g-r)-rgr)*1.05+Math.abs(l-rl)*.16+(Math.abs(r-rr)+Math.abs(g-rg)+Math.abs(b-rb))*.075};
 let m=new Uint8Array(w*h),q=new Int32Array(w*Math.max(2,h-top)),head=0,tail=0;
 function push(i,relaxed){if(m[i]||score(i)>(relaxed?47:38))return;m[i]=1;q[tail++]=i}
 for(let y=top;y<Math.min(h,top+Math.max(2,Math.round(3*dpr)));y++)for(let x=0;x<w;x++)push(y*w+x,false);
 while(head<tail){let i=q[head++],y=Math.floor(i/w),x=i-y*w;if(x)push(i-1,true);if(x+1<w)push(i+1,true);if(y>top)push(i-w,true);if(y+1<h)push(i+w,true)}
 return m;
}
function skyline(mask,w,h,top,dpr){
 let s=new Int32Array(w);for(let x=0;x<w;x++){let y=top;while(y<h&&mask[y*w+x])y++;s[x]=y}
 let r=Math.max(1,Math.round(1.25*dpr)),out=new Int32Array(w);for(let x=0;x<w;x++){let a=[];for(let n=Math.max(0,x-r);n<=Math.min(w-1,x+r);n++)a.push(s[n]);a.sort((p,q)=>p-q);out[x]=a[Math.floor(a.length/2)]}
 let jump=Math.max(14,Math.round(16*dpr)),span=Math.max(34,Math.round(56*dpr)),tol=Math.max(5,Math.round(5*dpr));
 for(let x=2;x<w-3;x++){if(out[x]-out[x-1]<jump)continue;let e=-1;for(let j=x+2;j<Math.min(w,x+span);j++)if(out[j-1]-out[j]>=jump*.72){e=j;break}if(e<0)continue;let bad=0,c=0;for(let k=x;k<e;k++){let t=(k-x+1)/(e-x+1),ch=lerp(out[x-1],out[e],t);if(out[k]>ch+tol)bad++;c++}if(bad/c<.5)continue;for(let k=x;k<e;k++){let t=(k-x+1)/(e-x+1);out[k]=Math.min(out[k],Math.round(lerp(out[x-1],out[e],t)))}x=e-1}
 return out;
}
function atkinson(paper,sky,w,h){let work=new Float32Array(paper),dots=new Uint8Array(w*h);const add=(x,y,e)=>{if(x>=0&&y>=0&&x<w&&y<h&&y>=sky[x])work[y*w+x]+=e};for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=y*w+x;if(y<sky[x]){work[i]=1;continue}let old=work[i],q=old>=.5?1:0;dots[i]=q?0:1;let e=(old-q)*.125;if(!e)continue;add(x+1,y,e);add(x+2,y,e);add(x-1,y+1,e);add(x,y+1,e);add(x+1,y+1,e);add(x,y+2,e)}return dots}
function makeTerrain(lum,sky,w,h,dpr){let paper=new Float32Array(w*h),dark=darkMQ.matches,th=theme();for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=y*w+x;if(y<sky[x]){paper[i]=1;continue}let v=lum[i]/255,d=dark?.06+.94*Math.pow(smooth(.06,.94,v),1.3):.02+.98*Math.pow(smooth(.04,.84,1-v),1.12);paper[i]=1-clamp(d,0,1)}let dots=atkinson(paper,sky,w,h),im=ctx.createImageData(w,h),o=im.data,rgb=parseInt(th.ink.slice(1),16),R=(rgb>>16)&255,G=(rgb>>8)&255,Bb=rgb&255,edge=Math.max(5,Math.round(7*dpr)),seed=w*13+h*29+701;for(let i=0;i<dots.length;i++){if(!dots[i])continue;let y=Math.floor(i/w),x=i-y*w,dist=y-sky[x],mix=smooth(0,edge,dist);if(dist<edge&&h2(x,y,seed)<(1-mix)*.19)continue;let p=i*4;o[p]=R;o[p+1]=G;o[p+2]=Bb;o[p+3]=Math.round(th.a*255*(.58+.42*mix))}return im}
function makeDust(){dust=[];let w=S.w,h=S.h,d=S.dpr,reach=Math.max(14,Math.round(22*d)),step=Math.max(1,Math.round(.85*d)),seed=w*17+h*31+811;for(let x=0;x<w;x+=step){let edge=S.sky[x];if(edge>=h)continue;for(let dist=1;dist<=reach;dist++){let y=edge-dist;if(y<0)break;let e=1-dist/(reach+1),keep=.018+e*e*.095;if(h2(x,y,seed)>keep)continue;dust.push({x,y,e,ph:h2(x,y,seed+3)*Math.PI*2,t:bayer(x,y),s:.55+h2(x,y,seed+7)*.65})}}}
function drawDust(now){let th=theme(),t=now*.000012;ctx.fillStyle=th.ink;for(let p of dust){let f=field(p.x*.0022,p.y*.0025+p.ph,t,991),pulse=.5+.5*Math.sin(p.ph+t*.34),den=p.e*(.26+f*.56+pulse*.18);if(den<p.t*.56)continue;let a=th.dust*p.e*p.s*smooth(.16,.78,den);if(a<.008)continue;ctx.globalAlpha=clamp(a,0,.25);ctx.fillRect(p.x,p.y-Math.round((f-.5)*2.2*S.dpr),1,1)}}
function valley(){let a=Math.floor(S.w*.16),b=Math.floor(S.w*.84),step=Math.max(2,Math.floor(S.w/220)),x=a,y=S.top;for(let i=a;i<=b;i+=step)if(S.sky[i]>y){x=i;y=S.sky[i]}return{x,y,depth:y-S.top}}
function makeClouds(){clouds=[];let v=valley();if(v.depth<24*S.dpr)return;let dark=S.dark,span=clamp(S.w*(dark?.52:.72),260*S.dpr,1300*S.dpr),hh=clamp(v.depth*(dark?.72:1.05),70*S.dpr,280*S.dpr),cy=v.y-hh*(dark?.18:.28),step=Math.max(2,Math.round((dark?3.1:2.7)*S.dpr)),seed=dark?1701:1801,density=dark?.34:.47;for(let y=cy-hh*.72;y<=v.y+hh*.36;y+=step)for(let x=v.x-span*.5;x<=v.x+span*.5;x+=step){if(x<0||x>=S.w||y<0||y>=S.h)continue;let u=(x-v.x)/(span*.5),z=(y-cy)/(hh*.5),shape=Math.exp(-(u*u*2.45+z*z*4.2))+.48*Math.exp(-((u+.46)**2*5.2+(z+.06)**2*6.3))+.42*Math.exp(-((u-.43)**2*5.4+(z+.02)**2*6));shape=clamp(shape,0,1);if(shape<.06)continue;let cx=Math.floor(x/step),yy=Math.floor(y/step);if(h2(cx,yy,seed)>.07+shape*density)continue;clouds.push({x,y,shape,ph:h2(cx,yy,seed+11)*17,t:bayer(cx,yy)})}}
function drawClouds(now){let th=theme(),t=now*.00001,swell=.84+.16*Math.sin(t*.33+.8);ctx.fillStyle=th.ink;for(let p of clouds){let ix=clamp(Math.round(p.x),0,S.w-1),mask=smooth(-110*S.dpr,30*S.dpr,S.sky[ix]-p.y),f=field(p.x*.0015+p.ph*.01,p.y*.0018,t,S.dark?1201:1401),den=p.shape*(.24+f*.76)*swell;if(den<p.t*(S.dark?.58:.49))continue;let a=th.cloud*mask*(.28+den*.72);if(a<.008)continue;ctx.globalAlpha=clamp(a,0,S.dark?.22:.34);ctx.fillRect(Math.round(p.x),Math.round(p.y),1,1)}}
function makeStars(){stars=[];if(!S.dark)return;let n=S.cssW<S.cssH?22:30,seed=S.w*41+S.h*73+1901,min=Math.sqrt(S.w*Math.max(1,S.top)/n)*.38,guard=0;while(stars.length<n&&guard++<n*1400){let x=Math.floor(hash(seed++)*S.w),maxY=Math.max(8*S.dpr,S.sky[x]-34*S.dpr);if(maxY<=10*S.dpr)continue;let q=hash(seed++);if(hash(seed++)>.55)q*=q;let y=Math.floor((.04+q*.86)*maxY),ok=true;for(let s of stars){let dx=s.x-x,dy=s.y-y;if(dx*dx+dy*dy<min*min){ok=false;break}}if(!ok)continue;let bright=hash(seed++)>.84;stars.push({x,y,size:bright?Math.max(1,Math.round(S.dpr*.72)):1,mag:bright?.78+hash(seed++)*.2:.3+hash(seed++)*.42,period:17000+hash(seed++)*41000,ph:hash(seed++)*Math.PI*2,bp:36000+hash(seed++)*85000,bo:hash(seed++)*100000})}}
function drawStars(now){if(!S.dark)return;let th=theme();ctx.fillStyle=th.star;for(let s of stars){let tw=.72+Math.sin(now/s.period*Math.PI*2+s.ph)*.17+Math.sin(now/(s.period*1.83)*Math.PI*2+s.ph*1.7)*.08,br=.76+.24*Math.sin((now+s.bo)/s.bp*Math.PI*2),edge=smooth(0,28*S.dpr,S.sky[clamp(Math.round(s.x),0,S.w-1)]-s.y),a=.86*s.mag*tw*br*edge;if(a<.012)continue;ctx.globalAlpha=clamp(a,0,1);ctx.fillRect(s.x,s.y,s.size,s.size)}}
function scheduleComet(now){if(!S.dark)return;let seed=Math.floor(now/1000)+S.w*3+S.h*5,dir=hash(seed)>.5?1:-1;comet.active=true;comet.start=now;comet.duration=1600+hash(seed+1)*1300;comet.x0=(.14+hash(seed+2)*.72)*S.w;comet.y0=(.07+hash(seed+3)*.24)*Math.max(S.top,1);comet.x1=comet.x0+dir*(.11+hash(seed+4)*.15)*S.w;comet.y1=comet.y0+(.08+hash(seed+5)*.11)*Math.max(S.top,1);comet.tail=(.018+hash(seed+6)*.022)*S.w;comet.next=now+comet.duration+150000+hash(seed+7)*240000}
function drawComet(now){if(!S.dark||!comet.active)return;let p=(now-comet.start)/comet.duration;if(p>=1){comet.active=false;return}let fade=smooth(0,.12,p)*(1-smooth(.72,1,p)),x=lerp(comet.x0,comet.x1,p),y=lerp(comet.y0,comet.y1,p),dx=comet.x1-comet.x0,dy=comet.y1-comet.y0,len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;ctx.fillStyle=theme().star;for(let n=comet.tail;n>0;n-=Math.max(1,S.dpr)){let tx=Math.round(x-dx*n),ty=Math.round(y-dy*n);if(tx<0||tx>=S.w||ty<0||ty>=S.h||ty>=S.sky[tx]-12*S.dpr)continue;let a=fade*Math.pow(1-n/comet.tail,1.5)*.65;if(a<.01)continue;ctx.globalAlpha=a;ctx.fillRect(tx,ty,1,1)}}
function build(){if(!plate.complete||!plate.naturalWidth)return;cancelAnimationFrame(raf);raf=0;let cssW=innerWidth,cssH=innerHeight,dpr=Math.min(devicePixelRatio||1,MAX_DPR),w=Math.max(1,Math.round(cssW*dpr)),h=Math.max(1,Math.round(cssH*dpr));canvas.width=w;canvas.height=h;canvas.style.width=cssW+'px';canvas.style.height=cssH+'px';buf.width=w;buf.height=h;bctx.clearRect(0,0,w,h);bctx.imageSmoothingEnabled=true;bctx.imageSmoothingQuality='high';let portrait=cssW<cssH,vis=Math.round(h*(portrait?.56:.52)),over=Math.round(h*(portrait?.18:.16)),drawH=vis+over,top=h-vis,ta=w/drawH,pw=plate.naturalWidth,ph=plate.naturalHeight,pa=pw/ph,sx=0,sy=0,sw=pw,sh=ph,focus=portrait?.55:.52;if(ta>pa){sh=pw/ta;sy=clamp(ph*.1,0,Math.max(0,ph-sh))}else{sw=ph*ta;sx=clamp(pw*focus-sw/2,0,Math.max(0,pw-sw))}bctx.drawImage(plate,sx,sy,sw,sh,0,top,w,drawH);let data=bctx.getImageData(0,0,w,h).data,lum=new Uint8Array(w*h);for(let i=top*w;i<lum.length;i++){let p=i*4;lum[i]=Math.round(data[p]*.2126+data[p+1]*.7152+data[p+2]*.0722)}let mask=skyMask(data,w,h,top,drawH,dpr),sky=skyline(mask,w,h,top,dpr),rt=h,rl=0;for(let y of sky){if(y<rt)rt=y;if(y<h&&y>rl)rl=y}S={w,h,cssW,cssH,dpr,dark:darkMQ.matches,sky,top:rt,low:rl};terrain=makeTerrain(lum,sky,w,h,dpr);makeDust();makeClouds();makeStars();let now=performance.now();comet.active=false;comet.next=S.dark?now+130000+h2(w,h,901)*160000:Infinity;draw(reduced?21437:now);if(!reduced)raf=requestAnimationFrame(tick)}
function draw(now){if(!S||!terrain)return;ctx.globalAlpha=1;ctx.clearRect(0,0,S.w,S.h);ctx.putImageData(terrain,0,0);drawDust(now);drawClouds(now);drawStars(now);drawComet(now);ctx.globalAlpha=1}
function tick(now){raf=requestAnimationFrame(tick);if(!S||reduced||!visible||now-last<1000/24)return;last=now;if(S.dark&&!comet.active&&now>=comet.next)scheduleComet(now);draw(now)}
function listen(m,f){m.addEventListener?m.addEventListener('change',f):m.addListener(f)}
listen(darkMQ,build);listen(motionMQ,e=>{reduced=e.matches;build()});addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(build,180)},{passive:true});document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible&&!reduced&&!raf)raf=requestAnimationFrame(tick)});
window.__portfolioSky={build,step:(n=performance.now())=>draw(reduced?21437:n),cometNow:(n=performance.now())=>{if(S?.dark)scheduleComet(n);draw(n)},state:()=>S?{width:S.w,height:S.h,cssWidth:S.cssW,cssHeight:S.cssH,dpr:S.dpr,dark:S.dark,ridgeTop:S.top,ridgeLow:S.low,ridgeDust:dust.length,cloudDots:clouds.length,stars:stars.length,motion:{reduced,visible,rafActive:!!raf}}:null};
plate.decoding='async';plate.onload=build;plate.onerror=()=>document.documentElement.setAttribute('data-plate-error','1');plate.src=SRC;
}
